var prefixList = {
    "Afghanistan": ["YA","T6"],
    "Agalega & St. Brandon Is.": ["3B6","3B7"],
    "Aland Is.": ["OH0"],
    "Alaska": ["KL","AL","NL","WL"],
    "Albania": ["ZA"],
    "Algeria": ["7T-7Y"],
    "American Samoa": ["KH8"],
    "Amsterdam & St. Paul Is.": ["FT/Z"],
    "Andaman & Nicobar Is.": ["VU4"],
    "Andorra": ["C3"],
    "Angola": ["D2","D3"],
    "Anguilla": ["VP2E"],
    "Annobon I.": ["3C0"],
    "Antarctica": ["CE9","KC4"],
    "Antigua & Barbuda": ["V2"],
    "Argentina": ["LO-LW"],
    "Armenia": ["EK"],
    "Aruba": ["P4"],
    "Ascension I.": ["ZD8"],
    "Asiatic Russia": ["UA-UI8","UA-UI9","UA-UI0","RA-RZ"],
    "Austral I.": ["FO","TX"],
    "Australia": ["VK","AX"],
    "Austria": ["OE"],
    "Aves I.": ["YV0"],
    "Azerbaijan": ["4J","4K"],
    "Azores": ["CU"],
    "Bahamas": ["C6"],
    "Bahrain": ["A9"],
    "Baker & Howland Is.": ["KH1"],
    "Balearic Is.": ["EA6-EH6"],
    "Banaba I. (Ocean I.)": ["T33"],
    "Bangladesh": ["S2"],
    "Barbados": ["8P"],
    "Belarus": ["EU","EW"],
    "Belgium": ["ON-OT"],
    "Belize": ["V3"],
    "Benin": ["TY"],
    "Bermuda": ["VP9"],
    "Bhutan": ["A5"],
    "Bolivia": ["CP"],
    "Bonaire": ["PJ4"],
    "Bosnia-Herzegovina": ["E7"],
    "Botswana": ["A2"],
    "Bouvet": ["3Y"],
    "Brazil": ["PP-PY","ZV-ZZ"],
    "British Virgin Is.": ["VP2V"],
    "Brunei Darussalam": ["V8"],
    "Bulgaria": ["LZ"],
    "Burkina Faso": ["XT"],
    "Burundi": ["9U"],
    "C. Kiribati (British Phoenix Is)": ["T31"],
    "Cambodia": ["XU"],
    "Cameroon": ["TJ"],
    "Canada": ["VA-VG","VO","VY"],
    "Canary Is.": ["EA8-EH8"],
    "Cape Verde": ["D4"],
    "Catalonia": ["EA3-EH3"],
    "Cayman Is.": ["ZF"],
    "Central Africa": ["TL"],
    "Ceuta & Melilla": ["EA9-EH9"],
    "Chad": ["TT"],
    "Chagos Is.": ["VQ9"],
    "Chatham Is.": ["ZL7"],
    "Chesterfield Is.": ["FK","TX"],
    "Chile": ["CA-CE"],
    "China": ["B"],
    "Christmas I.": ["VK9X"],
    "Clipperton I.": ["FO","TX"],
    "Cocos (Keeling) Is.": ["VK9C"],
    "Cocos I.": ["TI9"],
    "Colombia": ["HJ","HK","5J","5K"],
    "Comoros": ["D6"],
    "Congo (Republic of the)": ["TN"],
    "Conway Reef": ["3D2"],
    "Corsica": ["TK"],
    "Costa Rica": ["TI","TE"],
    "Cote d'Ivoire": ["TU"],
    "Crete": ["SV9","J49"],
    "Croatia": ["9A"],
    "Crozet I.": ["FT/W"],
    "Cuba": ["CM","CO"],
    "Curacao": ["PJ2"],
    "Cyprus": ["5B","C4","P3"],
    "Czech Republic": ["OK-OL"],
    "Dem. Rep. of Congo": ["9Q-9T"],
    "Denmark": ["OU-OW","OZ"],
    "Desecheo I.": ["KP5"],
    "Djibouti": ["J2"],
    "Dodecanese": ["SV5","J45"],
    "Dominica": ["J7"],
    "Dominican Republic": ["HI"],
    "DPR of Korea": ["P5"],
    "Ducie I.": ["VP6"],
    "E. Kiribati (Line Is.)": ["T32"],
    "East Malaysia": ["9M6","9M8"],
    "Easter I.": ["CE0"],
    "Ecuador": ["HC-HD"],
    "Egypt": ["SU"],
    "El Salvador": ["YS","HU"],
    "England": ["G","GX","M"],
    "Equatorial Guinea": ["3C"],
    "Eritrea": ["E3"],
    "Estonia": ["ES"],
    "Ethiopia": ["ET"],
    "European Russia": ["UA","UI1-7","RA-RZ"],
    "Falkland Is.": ["VP8/F"],
    "Faroe Is.": ["OY"],
    "Fed. Rep. of Germany": ["DA-DR"],
    "Fernando de Noronha": ["PP0-PY0F"],
    "Fiji": ["3D2"],
    "Finland": ["OF-OI"],
    "France": ["F"],
    "Franz Josef Land": ["R1/F"],
    "French Guiana": ["FY"],
    "French Polynesia": ["FO","TX"],
    "Gabon": ["TR"],
    "Galapagos Is.": ["HC8-HD8"],
    "Georgia": ["4L"],
    "Ghana": ["9G"],
    "Gibraltar": ["ZB2"],
    "Glorioso Is.": ["FT/G","TO"],
    "Greece": ["SV-SZ","J4"],
    "Greenland": ["OX"],
    "Grenada": ["J3"],
    "Guadeloupe": ["FG","TO"],
    "Guam": ["KH2"],
    "Guantanamo Bay": ["KG4"],
    "Guatemala": ["TG","TD"],
    "Guernsey": ["GU","GP"],
    "Guinea": ["3X"],
    "Guinea-Bissau": ["J5"],
    "Guyana": ["8R"],
    "Haiti": ["HH"],
    "Hawaii": ["KH6","KH7"],
    "Heard I.": ["VK0"],
    "Honduras": ["HQ","HR"],
    "Hong Kong": ["VR"],
    "Hungary": ["HA","HG"],
    "Iceland": ["TF"],
    "India": ["VU"],
    "Indonesia": ["YB-YH"],
    "Iran": ["EP-EQ"],
    "Iraq": ["YI"],
    "Ireland": ["EI-EJ"],
    "Isle of Man": ["GD","GT"],
    "Israel": ["4X","4Z"],
    "Italy": ["I"],
    "ITU HQ": ["4U_ITU"],
    "Jamaica": ["6Y"],
    "Jan Mayen": ["JX"],
    "Japan": ["JA-JS","7J-7N"],
    "Jersey": ["GJ","GH"],
    "Johnston I.": ["KH3"],
    "Jordan": ["JY"],
    "Juan de Nova, Europa": ["FT/J","E","TO"],
    "Juan Fernandez Is.": ["CE0"],
    "Kaliningrad": ["UA2","RA2"],
    "Kazakhstan": ["UN-UQ"],
    "Kenya": ["5Y-5Z"],
    "Kerguelen Is.": ["FT/X"],
    "Kermadec Is.": ["ZL8"],
    "Kingdom of Eswatini": ["3DA"],
    "Kure I.": ["KH7K"],
    "Kuwait": ["9K"],
    "Kyrgyzstan": ["EX"],
    "Lakshadweep Is.": ["VU7"],
    "Laos": ["XW"],
    "Latvia": ["YL"],
    "Lebanon": ["OD"],
    "Lesotho": ["7P"],
    "Liberia": ["EL"],
    "Libya": ["5A"],
    "Liechtenstein": ["HB0"],
    "Lithuania": ["LY"],
    "Lord Howe I.": ["VK9L"],
    "Luxembourg": ["LX"],
    "Macao": ["XX9"],
    "Macquarie I.": ["VK0"],
    "Madagascar": ["5R"],
    "Madeira Is.": ["CT3"],
    "Malawi": ["7Q"],
    "Maldives": ["8Q"],
    "Mali": ["TZ"],
    "Malpelo I.": ["HK0"],
    "Malta": ["9H"],
    "Mariana Is.": ["KH0"],
    "Market Reef": ["OJ0"],
    "Marquesas Is.": ["FO","TX"],
    "Marshall Is.": ["V7"],
    "Martinique": ["FM","TO"],
    "Mauritania": ["5T"],
    "Mauritius": ["3B8"],
    "Mayotte": ["FH","TO"],
    "Mellish Reef": ["VK9M"],
    "Mexico": ["XA-XI"],
    "Micronesia": ["V6"],
    "Midway I.": ["KH4"],
    "Minami Torishima": ["JD1"],
    "Moldova": ["ER"],
    "Monaco": ["3A"],
    "Mongolia": ["JT-JV"],
    "Montenegro": ["4O"],
    "Montserrat": ["VP2M"],
    "Morocco": ["CN"],
    "Mount Athos": ["SV/A"],
    "Mozambique": ["C8-C9"],
    "Myanmar": ["XY-XZ"],
    "N. Cook Is.": ["E5"],
    "Namibia": ["V5"],
    "Nauru": ["C2"],
    "Navassa I.": ["KP1"],
    "Nepal": ["9N"],
    "Netherlands": ["PA-PI"],
    "New Caledonia": ["FK","TX"],
    "New Zealand": ["ZL-ZM"],
    "New Zealand - Subantarctic Islands": ["ZL9"],
    "Nicaragua": ["YN","H6-7","HT"],
    "Niger": ["5U"],
    "Nigeria": ["5N"],
    "Niue": ["E6"],
    "Norfolk I.": ["VK9N"],
    "North Macedonia": ["Z3"],
    "Northern Ireland": ["GI","GN"],
    "Norway": ["LA-LN"],
    "Ogasawara": ["JD1"],
    "Oman": ["A4"],
    "Pakistan": ["AP"],
    "Palau": ["T8"],
    "Palestine": ["E4"],
    "Palmyra & Jarvis Is.": ["KH5"],
    "Panama": ["HO","HP"],
    "Papua New Guinea": ["P2"],
    "Paraguay": ["ZP"],
    "Peru": ["OA-OC"],
    "Peter 1 I.": ["3Y"],
    "Philippines": ["DU-DZ","4D-4I"],
    "Pitcairn I.": ["VP6"],
    "Poland": ["SN","SR"],
    "Portugal": ["CT"],
    "Pratas I.": ["BV9P"],
    "Prince Edward & Marion Is.": ["ZS8"],
    "Puerto Rico": ["KP3","KP4"],
    "Qatar": ["A7"],
    "Republic of Korea": ["HL","6K-6N"],
    "Kosovo*": ["Z6"],
    "Reunion I.": ["FR","TO"],
    "Revillagigedo": ["XA4-XI4"],
    "Rodrigues I.": ["3B9"],
    "Romania": ["YO-YR"],
    "Rotuma I.": ["3D2"],
    "Rwanda": ["9X"],
    "S. Cook Is.": ["E5"],
    "Saba & St. Eustatius": ["PJ5","PJ6"],
    "Sable I.": ["CY0"],
    "Saint Barthelemy": ["FJ","TO"],
    "Saint Martin": ["FS","TO"],
    "Samoa": ["5W"],
    "San Andres & Providencia": ["HK0"],
    "San Felix & San Ambrosio": ["CE0"],
    "San Marino": ["T7"],
    "Sao Tome & Principe": ["S9"],
    "Sardinia": ["IS0","IM0"],
    "Saudi Arabia": ["HZ"],
    "Scarborough Reef": ["BS7"],
    "Scotland": ["GM","GS"],
    "Senegal": ["6V-6W"],
    "Serbia": ["YT-YU"],
    "Seychelles": ["S7"],
    "Sierra Leone": ["9L"],
    "Singapore": ["9V"],
    "Sint Maarten": ["PJ7"],
    "Slovak Republic": ["OM"],
    "Slovenia": ["S5"],
    "Solomon Is.": ["H4"],
    "Somalia": ["T5","6O"],
    "South Africa": ["ZR-ZU"],
    "South Georgia I.": ["VP8/G","LU"],
    "South Orkney Is.": ["VP8/O","LU"],
    "South Sandwich Is.": ["VP8/SA","LU"],
    "South Shetland Is.": ["VP8/SH","LU","4K1"],
    "South Sudan (Rep of)": ["Z8"],
    "Sov. Mil. Order of Malta": ["1A"],
    "Spain": ["EA-EH"],
    "Spratly Is.": ["1S"],
    "Sri Lanka": ["4S"],
    "St. Helena": ["ZD7"],
    "St. Kitts & Nevis": ["V4"],
    "St. Lucia": ["J6"],
    "St. Paul I.": ["CY9"],
    "St. Peter & St. Paul Rocks": ["PP0-PY0S"],
    "St. Pierre & Miquelon": ["FP"],
    "St. Vincent": ["J8"],
    "Sudan": ["ST"],
    "Suriname": ["PZ"],
    "Svalbard": ["JW"],
    "Swains I.": ["KH8"],
    "Sweden": ["SA-SM","7S-8S"],
    "Switzerland": ["HB"],
    "Syria": ["YK"],
    "Taiwan": ["BU-BX"],
    "Tajikistan": ["EY"],
    "Tanzania": ["5H-5I"],
    "Temotu Province": ["H40"],
    "Thailand": ["HS","E2"],
    "The Gambia": ["C5"],
    "Timor - Leste": ["4W"],
    "Togo": ["5V"],
    "Tokelau Is.": ["ZK3"],
    "Tonga": ["A3"],
    "Trindade & Martim Vaz Is.": ["PP0-PY0T"],
    "Trinidad & Tobago": ["9Y-9Z"],
    "Tristan da Cunha & Gough I.": ["ZD9"],
    "Tromelin I.": ["FT/T","TO"],
    "Tunisia": ["3V"],
    "Turkey": ["TA-TC"],
    "Turkmenistan": ["EZ"],
    "Turks & Caicos Is.": ["VP5"],
    "Tuvalu": ["T2"],
    "Uganda": ["5X"],
    "UK Sov. Base Areas on Cyprus": ["ZC4"],
    "Ukraine": ["UR-UZ","EM-EO"],
    "United Arab Emirates": ["A6"],
    "United Nations HQ": ["4U_UN"],
    "United States of America": ["K","W","N","AA-AK"],
    "Uruguay": ["CV-CX"],
    "Uzbekistan": ["UJ-UM"],
    "Vanuatu": ["YJ"],
    "Vatican": ["HV"],
    "Venezuela": ["YV-YY","4M"],
    "Viet Nam": ["3W","XV"],
    "Virgin Is.": ["KP2"],
    "W. Kiribati (Gilbert Is. )": ["T30"],
    "Wake I.": ["KH9"],
    "Wales": ["GW","GC"],
    "Wallis & Futuna Is.": ["FW"],
    "West Malaysia": ["9M2","9M4"],
    "Western Sahara": ["S0"],
    "Willis I.": ["VK9W"],
    "Yemen": ["7O"],
    "Zambia": ["9I","9J"],
    "Zimbabwe": ["Z2"]
}

var prefixListForLookup = {
    "Afghanistan": ["YA","T6"],
    "Agalega & St. Brandon Is.": ["3B6","3B7"],
    "Aland Is.": ["OH0"],
    "Alaska": ["KL","AL","NL","WL"],
    "Albania": ["ZA"],
    "Algeria": ["7T", "7U", "7V", "7W", "7X", "7Y"],
    "American Samoa": ["KH8"],
    "Amsterdam & St. Paul Is.": ["FT/Z"],
    "Andaman & Nicobar Is.": ["VU4"],
    "Andorra": ["C3"],
    "Angola": ["D2","D3"],
    "Anguilla": ["VP2E"],
    "Annobon I.": ["3C0"],
    "Antarctica": ["CE9","KC4"],
    "Antigua & Barbuda": ["V2"],
    "Argentina": ["LO", "LP", "LQ", "LR", "LS", "LT", "LU", "LV", "LW"],
    "Armenia": ["EK"],
    "Aruba": ["P4"],
    "Ascension I.": ["ZD8"],
    "Asiatic Russia": ["UA8", "UB8", "UC8", "UD8", "UE8", "UF8", "UG8", "UH8", "UI8", "UA9", "UB9", "UC9", "UD9", "UE9", "UF9", "UG9", "UH9", "UI9", "UA0", "UB0", "UC0", "UD0", "UE0", "UF0", "UG0", "UH0", "UI0","RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RQ", "RR", "RS", "RT", "RU", "RV", "RW", "RX", "RY", "RZ"],
    "Austral I.": ["FO","TX"],
    "Australia": ["VK","AX"],
    "Austria": ["OE"],
    "Aves I.": ["YV0"],
    "Azerbaijan": ["4J","4K"],
    "Azores": ["CU"],
    "Bahamas": ["C6"],
    "Bahrain": ["A9"],
    "Baker & Howland Is.": ["KH1"],
    "Balearic Is.": ["EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH"],
    "Banaba I. (Ocean I.)": ["T33"],
    "Bangladesh": ["S2"],
    "Barbados": ["8P"],
    "Belarus": ["EU","EW"],
    "Belgium": ["ON", "OO", "OP", "OQ", "OR", "OS", "OT"],
    "Belize": ["V3"],
    "Benin": ["TY"],
    "Bermuda": ["VP9"],
    "Bhutan": ["A5"],
    "Bolivia": ["CP"],
    "Bonaire": ["PJ4"],
    "Bosnia-Herzegovina": ["E7"],
    "Botswana": ["A2"],
    "Bouvet": ["3Y"],
    "Brazil": ["PP", "PQ", "PR", "PS", "PT", "PU", "PV", "PW", "PX", "PY","ZV", "ZW", "ZX", "ZY", "ZZ"],
    "British Virgin Is.": ["VP2V"],
    "Brunei Darussalam": ["V8"],
    "Bulgaria": ["LZ"],
    "Burkina Faso": ["XT"],
    "Burundi": ["9U"],
    "C. Kiribati (British Phoenix Is)": ["T31"],
    "Cambodia": ["XU"],
    "Cameroon": ["TJ"],
    "Canada": ["VA", "VB", "VC", "VD", "VE", "VF", "VG","VO","VY"],
    "Canary Is.": ["EA8", "EB8", "EC8", "ED8", "EE8", "EF8", "EG8", "EH8"],
    "Cape Verde": ["D4"],
    "Catalonia": ["EA3", "EB3", "EC3", "ED3", "EE3", "EF3", "EG3", "EH3"],
    "Cayman Is.": ["ZF"],
    "Central Africa": ["TL"],
    "Ceuta & Melilla": ["EA9", "EB9", "EC9", "ED9", "EE9", "EF9", "EG9", "EH9"],
    "Chad": ["TT"],
    "Chagos Is.": ["VQ9"],
    "Chatham Is.": ["ZL7"],
    "Chesterfield Is.": ["FK","TX"],
    "Chile": ["CA", "CB", "CC", "CD", "CE"],
    "China": ["B"],
    "Christmas I.": ["VK9X"],
    "Clipperton I.": ["FO","TX"],
    "Cocos (Keeling) Is.": ["VK9C"],
    "Cocos I.": ["TI9"],
    "Colombia": ["HJ","HK","5J","5K"],
    "Comoros": ["D6"],
    "Congo (Republic of the)": ["TN"],
    "Conway Reef": ["3D2"],
    "Corsica": ["TK"],
    "Costa Rica": ["TI","TE"],
    "Cote d'Ivoire": ["TU"],
    "Crete": ["SV9","J49"],
    "Croatia": ["9A"],
    "Crozet I.": ["FT/W"],
    "Cuba": ["CM","CO"],
    "Curacao": ["PJ2"],
    "Cyprus": ["5B","C4","P3"],
    "Czech Republic": ["OK", "OL"],
    "Dem. Rep. of Congo": ["9Q", "9R", "9S", "9T"],
    "Denmark": ["OU", "OV", "OW","OZ"],
    "Desecheo I.": ["KP5"],
    "Djibouti": ["J2"],
    "Dodecanese": ["SV5","J45"],
    "Dominica": ["J7"],
    "Dominican Republic": ["HI"],
    "DPR of Korea": ["P5"],
    "Ducie I.": ["VP6"],
    "E. Kiribati (Line Is.)": ["T32"],
    "East Malaysia": ["9M6","9M8"],
    "Easter I.": ["CE0"],
    "Ecuador": ["HC","HD"],
    "Egypt": ["SU"],
    "El Salvador": ["YS","HU"],
    "England": ["G","GX","M"],
    "Equatorial Guinea": ["3C"],
    "Eritrea": ["E3"],
    "Estonia": ["ES"],
    "Ethiopia": ["ET"],
    "European Russia": ["UA","UI1", "UI2", "UI3", "UI4", "UI5", "UI6", "UI7","RA", "RB", "RC", "RD", "RE", "RF", "RG", "RH", "RI", "RJ", "RK", "RL", "RM", "RN", "RO", "RP", "RQ", "RR", "RS", "RT", "RU", "RV", "RW", "RX", "RY", "RZ"],
    "Falkland Is.": ["VP8/F"],
    "Faroe Is.": ["OY"],
    "Fed. Rep. of Germany": ["DA", "DB", "DC", "DD", "DE", "DF", "DG", "DH", "DI", "DJ", "DK", "DL", "DM", "DN", "DO", "DP", "DQ", "DR"],
    "Fernando de Noronha": ["PP0","PY0F"],
    "Fiji": ["3D2"],
    "Finland": ["OF", "OG", "OH", "OI"],
    "France": ["F"],
    "Franz Josef Land": ["R1/F"],
    "French Guiana": ["FY"],
    "French Polynesia": ["FO","TX"],
    "Gabon": ["TR"],
    "Galapagos Is.": ["HC8","HD8"],
    "Georgia": ["4L"],
    "Ghana": ["9G"],
    "Gibraltar": ["ZB2"],
    "Glorioso Is.": ["FT/G","TO"],
    "Greece": ["SV", "SW", "SX", "SY", "SZ","J4"],
    "Greenland": ["OX"],
    "Grenada": ["J3"],
    "Guadeloupe": ["FG","TO"],
    "Guam": ["KH2"],
    "Guantanamo Bay": ["KG4"],
    "Guatemala": ["TG","TD"],
    "Guernsey": ["GU","GP"],
    "Guinea": ["3X"],
    "Guinea-Bissau": ["J5"],
    "Guyana": ["8R"],
    "Haiti": ["HH"],
    "Hawaii": ["KH6","KH7"],
    "Heard I.": ["VK0"],
    "Honduras": ["HQ","HR"],
    "Hong Kong": ["VR"],
    "Hungary": ["HA","HG"],
    "Iceland": ["TF"],
    "India": ["VU"],
    "Indonesia": ["YB", "YC", "YD", "YE", "YF", "YG", "YH"],
    "Iran": ["EP","EQ"],
    "Iraq": ["YI"],
    "Ireland": ["EI","EJ"],
    "Isle of Man": ["GD","GT"],
    "Israel": ["4X","4Z"],
    "Italy": ["I"],
    "ITU HQ": ["4U_ITU"],
    "Jamaica": ["6Y"],
    "Jan Mayen": ["JX"],
    "Japan": ["JA", "JB", "JC", "JD", "JE", "JF", "JG", "JH", "JI", "JJ", "JK", "JL", "JM", "JN", "JO", "JP", "JQ", "JR", "JS","7J", "7K", "7L", "7M", "7N"],
    "Jersey": ["GJ","GH"],
    "Johnston I.": ["KH3"],
    "Jordan": ["JY"],
    "Juan de Nova, Europa": ["FT/J","E","TO"],
    "Juan Fernandez Is.": ["CE0"],
    "Kaliningrad": ["UA2","RA2"],
    "Kazakhstan": ["UN", "UO", "UP", "UQ"],
    "Kenya": ["5Y","5Z"],
    "Kerguelen Is.": ["FT/X"],
    "Kermadec Is.": ["ZL8"],
    "Kingdom of Eswatini": ["3DA"],
    "Kure I.": ["KH7K"],
    "Kuwait": ["9K"],
    "Kyrgyzstan": ["EX"],
    "Lakshadweep Is.": ["VU7"],
    "Laos": ["XW"],
    "Latvia": ["YL"],
    "Lebanon": ["OD"],
    "Lesotho": ["7P"],
    "Liberia": ["EL"],
    "Libya": ["5A"],
    "Liechtenstein": ["HB0"],
    "Lithuania": ["LY"],
    "Lord Howe I.": ["VK9L"],
    "Luxembourg": ["LX"],
    "Macao": ["XX9"],
    "Macquarie I.": ["VK0"],
    "Madagascar": ["5R"],
    "Madeira Is.": ["CT3"],
    "Malawi": ["7Q"],
    "Maldives": ["8Q"],
    "Mali": ["TZ"],
    "Malpelo I.": ["HK0"],
    "Malta": ["9H"],
    "Mariana Is.": ["KH0"],
    "Market Reef": ["OJ0"],
    "Marquesas Is.": ["FO","TX"],
    "Marshall Is.": ["V7"],
    "Martinique": ["FM","TO"],
    "Mauritania": ["5T"],
    "Mauritius": ["3B8"],
    "Mayotte": ["FH","TO"],
    "Mellish Reef": ["VK9M"],
    "Mexico": ["XA", "XB", "XC", "XD", "XE", "XF", "XG", "XH", "XI"],
    "Micronesia": ["V6"],
    "Midway I.": ["KH4"],
    "Minami Torishima": ["JD1"],
    "Moldova": ["ER"],
    "Monaco": ["3A"],
    "Mongolia": ["JT", "JU", "JV"],
    "Montenegro": ["4O"],
    "Montserrat": ["VP2M"],
    "Morocco": ["CN"],
    "Mount Athos": ["SV/A"],
    "Mozambique": ["C8","C9"],
    "Myanmar": ["XY","XZ"],
    "N. Cook Is.": ["E5"],
    "Namibia": ["V5"],
    "Nauru": ["C2"],
    "Navassa I.": ["KP1"],
    "Nepal": ["9N"],
    "Netherlands": ["PA", "PB", "PC", "PD", "PE", "PF", "PG", "PH", "PI"],
    "New Caledonia": ["FK","TX"],
    "New Zealand": ["ZL","ZM"],
    "New Zealand - Subantarctic Islands": ["ZL9"],
    "Nicaragua": ["YN","H6", "H7","HT"],
    "Niger": ["5U"],
    "Nigeria": ["5N"],
    "Niue": ["E6"],
    "Norfolk I.": ["VK9N"],
    "North Macedonia": ["Z3"],
    "Northern Ireland": ["GI","GN"],
    "Norway": ["LA", "LB", "LC", "LD", "LE", "LF", "LG", "LH", "LI", "LJ", "LK", "LL", "LM", "LN"],
    "Ogasawara": ["JD1"],
    "Oman": ["A4"],
    "Pakistan": ["AP"],
    "Palau": ["T8"],
    "Palestine": ["E4"],
    "Palmyra & Jarvis Is.": ["KH5"],
    "Panama": ["HO","HP"],
    "Papua New Guinea": ["P2"],
    "Paraguay": ["ZP"],
    "Peru": ["OA", "OB", "OC"],
    "Peter 1 I.": ["3Y"],
    "Philippines": ["DU", "DV", "DW", "DX", "DY", "DZ","4D", "4E", "4F", "4G", "4H", "4I"],
    "Pitcairn I.": ["VP6"],
    "Poland": ["SN","SR"],
    "Portugal": ["CT"],
    "Pratas I.": ["BV9P"],
    "Prince Edward & Marion Is.": ["ZS8"],
    "Puerto Rico": ["KP3","KP4"],
    "Qatar": ["A7"],
    "Republic of Korea": ["HL","6K", "6L", "6M", "6N"],
    "Kosovo*": ["Z6"],
    "Reunion I.": ["FR","TO"],
    "Revillagigedo": ["XA4", "XB4", "XC4", "XD4", "XE4", "XF4", "XG4", "XH4", "XI4"],
    "Rodrigues I.": ["3B9"],
    "Romania": ["YO", "YP", "YQ", "YR"],
    "Rotuma I.": ["3D2"],
    "Rwanda": ["9X"],
    "S. Cook Is.": ["E5"],
    "Saba & St. Eustatius": ["PJ5","PJ6"],
    "Sable I.": ["CY0"],
    "Saint Barthelemy": ["FJ","TO"],
    "Saint Martin": ["FS","TO"],
    "Samoa": ["5W"],
    "San Andres & Providencia": ["HK0"],
    "San Felix & San Ambrosio": ["CE0"],
    "San Marino": ["T7"],
    "Sao Tome & Principe": ["S9"],
    "Sardinia": ["IS0","IM0"],
    "Saudi Arabia": ["HZ"],
    "Scarborough Reef": ["BS7"],
    "Scotland": ["GM","GS"],
    "Senegal": ["6V","6W"],
    "Serbia": ["YT","YU"],
    "Seychelles": ["S7"],
    "Sierra Leone": ["9L"],
    "Singapore": ["9V"],
    "Saint Maarten": ["PJ7"],
    "Slovak Republic": ["OM"],
    "Slovenia": ["S5"],
    "Solomon Is.": ["H4"],
    "Somalia": ["T5","6O"],
    "South Africa": ["ZR", "ZS", "ZT", "ZU"],
    "South Georgia I.": ["VP8/G","LU"],
    "South Orkney Is.": ["VP8/O","LU"],
    "South Sandwich Is.": ["VP8/SA","LU"],
    "South Shetland Is.": ["VP8/SH","LU","4K1"],
    "South Sudan (Rep of)": ["Z8"],
    "Sov. Mil. Order of Malta": ["1A"],
    "Spain": ["EA", "EB", "EC", "ED", "EE", "EF", "EG", "EH"],
    "Spratly Is.": ["1S"],
    "Sri Lanka": ["4S"],
    "St. Helena": ["ZD7"],
    "St. Kitts & Nevis": ["V4"],
    "St. Lucia": ["J6"],
    "St. Paul I.": ["CY9"],
    "St. Peter & St. Paul Rocks": ["PP0","PY0S"],
    "St. Pierre & Miquelon": ["FP"],
    "St. Vincent": ["J8"],
    "Sudan": ["ST"],
    "Suriname": ["PZ"],
    "Svalbard": ["JW"],
    "Swains I.": ["KH8"],
    "Sweden": ["SA", "SB", "SC", "SD", "SE", "SF", "SG", "SH", "SI", "SJ", "SK", "SL", "SM","7S","8S"],
    "Switzerland": ["HB"],
    "Syria": ["YK"],
    "Taiwan": ["BU", "BV", "BW", "BX"],
    "Tajikistan": ["EY"],
    "Tanzania": ["5H","5I"],
    "Temotu Province": ["H40"],
    "Thailand": ["HS","E2"],
    "The Gambia": ["C5"],
    "Timor - Leste": ["4W"],
    "Togo": ["5V"],
    "Tokelau Is.": ["ZK3"],
    "Tonga": ["A3"],
    "Trindade & Martim Vaz Is.": ["PP0","PY0T"],
    "Trinidad & Tobago": ["9Y","9Z"],
    "Tristan da Cunha & Gough I.": ["ZD9"],
    "Tromelin I.": ["FT/T","TO"],
    "Tunisia": ["3V"],
    "Turkey": ["TA", "TB", "TC"],
    "Turkmenistan": ["EZ"],
    "Turks & Caicos Is.": ["VP5"],
    "Tuvalu": ["T2"],
    "Uganda": ["5X"],
    "UK Sov. Base Areas on Cyprus": ["ZC4"],
    "Ukraine": ["UR", "US", "UT", "UU", "UV", "UW", "UX", "UY", "UZ","EM", "EN", "EO"],
    "United Arab Emirates": ["A6"],
    "United Nations HQ": ["4U_UN"],
    "United States of America": ["K","W","N","AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK"],
    "Uruguay": ["CV", "CW", "CX"],
    "Uzbekistan": ["UJ", "UK", "UL", "UM"],
    "Vanuatu": ["YJ"],
    "Vatican": ["HV"],
    "Venezuela": ["YV", "YW", "YX", "YY","4M"],
    "Viet Nam": ["3W","XV"],
    "Virgin Is.": ["KP2"],
    "W. Kiribati (Gilbert Is. )": ["T30"],
    "Wake I.": ["KH9"],
    "Wales": ["GW","GC"],
    "Wallis & Futuna Is.": ["FW"],
    "West Malaysia": ["9M2","9M4"],
    "Western Sahara": ["S0"],
    "Willis I.": ["VK9W"],
    "Yemen": ["7O"],
    "Zambia": ["9I","9J"],
    "Zimbabwe": ["Z2"]
}
