const prefixList = {
	"Afghanistan":["T6","YA"],
	"Albania (Republic of)":["ZA"],
	"Algeria (People's Democratic Republic of)":["7R","7T","7U","7V","7W","7X","7Y"],
	"Andorra (Principality of)":["C3"],
	"Angola (Republic of)":["D2","D3"],
	"Antigua and Barbuda":["V2"],
	"Argentine Republic":["AY","AZ","L2","L3","L4","L5","L6","L7","L8","L9","LO","LP","LQ","LR","LS","LT","LU","LV","LW"],
	"Armenia (Republic of)":["EK"],
	"Australia":["AX","VH","VI","VJ","VK","VL","VM","VN","VZ"],
	"Austria":["OE"],
	"Azerbaijan (Republic of)":["4J","4K"],
	"Bahamas (Commonwealth of the)":["C6"],
	"Bahrain (Kingdom of)":["A9"],
	"Bangladesh (People's Republic of)":["S2","S3"],
	"Barbados":["8P"],
	"Belarus (Republic of)":["EU","EV","EW"],
	"Belgium":["ON","OO","OP","OQ","OR","OS","OT"],
	"Belize":["V3"],
	"Benin (Republic of)":["TY"],
	"Bhutan (Kingdom of)":["A5"],
	"Bolivia (Plurinational State of)":["CP"],
	"Bosnia and Herzegovina":["E7"],
	"Botswana (Republic of)":["8O","A2"],
	"Brazil (Federative Republic of)":["PP","PQ","PR","PS","PT","PU","PV","PW","PX","PY","ZV","ZW","ZX","ZY","ZZ"],
	"Brunei Darussalam":["V8"],
	"Bulgaria (Republic of)":["LZ"],
	"Burkina Faso":["XT"],
	"Burundi (Republic of)":["9U"],
	"Cabo Verde (Republic of)":["D4"],
	"Cambodia (Kingdom of)":["XU"],
	"Cameroon (Republic of)":["TJ"],
	"Canada":["CF","CG","CH","CI","CJ","CK","CY","CZ","VA","VB","VC","VD","VE","VF","VG","VO","VX","VY","XJ","XK","XL","XM","XN","XO"],
	"Central African Republic":["TL"],
	"Chad (Republic of)":["TT"],
	"Chile":["3G","CA","CB","CC","CD","CE","XQ","XR"],
	"China - Hong Kong":["VR"],
	"China - Macao":["XX"],
	"China (People's Republic of)":["3H","3I","3J","3K","3L","3M","3N","3O","3P","3Q","3R","3S","3T","3U","BA","BB","BC","BD","BE","BF","BG","BH","BI","BJ","BK","BL","BM","BN","BO","BP","BQ","BR","BS","BT","BU","BV","BW","BX","BY","BZ","XS"],
	"Colombia (Republic of)":["5J","5K","HJ","HK"],
	"Comoros (Union of the)":["D6"],
	"Congo (Republic of the)":["TN"],
	"Costa Rica":["TE","TI"],
	"Croatia (Republic of)":["9A"],
	"Cuba":["CL","CM","CO","T4"],
	"Cyprus (Republic of)":["5B","C4","H2","P3"],
	"Czech Republic":["OK","OL"],
	"Côte d'Ivoire (Republic of)":["TU"],
	"Democratic People's Republic of Korea":["HM","P5","P6","P7","P8","P9"],
	"Democratic Republic of the Congo":["9O","9P","9Q","9R","9S","9T"],
	"Denmark":["5P","5Q","OU","OV","OW","OX","OY","OZ","XP"],
	"Djibouti (Republic of)":["J2"],
	"Dominica (Commonwealth of)":["J7"],
	"Dominican Republic":["HI"],
	"Ecuador":["HC","HD"],
	"Egypt (Arab Republic of)":["6A","6B","SSM","SU"],
	"El Salvador (Republic of)":["HU","YS"],
	"Equatorial Guinea (Republic of)":["3C"],
	"Eritrea":["E3"],
	"Estonia (Republic of)":["ES"],
	"Eswatini (Kingdom of)":["3DM"],
	"Ethiopia (Federal Democratic Republic of)":["9E","9F","ET"],
	"Fiji (Republic of)":["3DZ"],
	"Finland":["OF","OG","OH","OI","OJ"],
	"France":["FA","FB","FC","FD","FE","FF","FG","FH","FI","FJ","FK","FL","FM","FN","FO","FP","FQ","FR","FS","FT","FU","FV","FW","FX","FY","FZ","HW","HX","HY","TH","TK","TM","TO","TP","TQ","TV","TW","TX"],
	"Gabonese Republic":["TR"],
	"Gambia (Republic of the)":["C5"],
	"Georgia":["4L"],
	"Germany (Federal Republic of)":["DA","DB","DC","DD","DE","DF","DG","DH","DI","DJ","DK","DL","DM","DN","DO","DP","DQ","DR","Y2","Y3","Y4","Y5","Y6","Y7","Y8","Y9"],
	"Ghana":["9G"],
	"Greece":["J4","SV","SW","SX","SY","SZ"],
	"Grenada":["J3"],
	"Guatemala (Republic of)":["TD","TG"],
	"Guinea (Republic of)":["3X"],
	"Guinea-Bissau (Republic of)":["J5"],
	"Guyana":["8R"],
	"Haiti (Republic of)":["4V","HH"],
	"Honduras (Republic of)":["HQ","HR"],
	"Hungary":["HA","HG"],
	"Iceland":["TF"],
	"India (Republic of)":["8T","8U","8V","8W","8X","8Y","AT","AU","AV","AW","VT","VU","VV","VW"],
	"Indonesia (Republic of)":["7A","7B","7C","7D","7E","7F","7G","7H","7I","8A","8B","8C","8D","8E","8F","8G","8H","8I","JZ","PK","PL","PM","PN","PO","YB","YC","YD","YE","YF","YG","YH"],
	"Iran (Islamic Republic of)":["9B","9C","9D","EP","EQ"],
	"Iraq (Republic of)":["HN","YI"],
	"Ireland":["EI","EJ"],
	"Israel (State of)":["4X","4Z"],
	"Italy":["IA","IB","IC","ID","IE","IF","IG","IH","II","IJ","IK","IL","IM","IN","IO","IP","IQ","IR","IS","IT","IU","IV","IW","IX","IY","IZ"],
	"Jamaica":["6Y"],
	"Japan":["7J","7K","7L","7M","7N","8J","8K","8L","8M","8N","JA","JB","JC","JD","JE","JF","JG","JH","JI","JJ","JK","JL","JM","JN","JO","JP","JQ","JR","JS"],
	"Jordan (Hashemite Kingdom of)":["JY"],
	"Kazakhstan (Republic of)":["UN","UO","UP","UQ"],
	"Kenya (Republic of)":["5Y","5Z"],
	"Kiribati (Republic of)":["T3"],
	"Korea (Republic of)":["6K","6L","6M","6N","D7","D8","D9","DS","DT","HL"],
	"Kuwait (State of)":["9K"],
	"Kyrgyz Republic":["EX"],
	"Lao People's Democratic Republic":["XW"],
	"Latvia (Republic of)":["YL"],
	"Lebanon":["OD"],
	"Lesotho (Kingdom of)":["7P"],
	"Liberia (Republic of)":["5L","5M","6Z","A8","D5","EL"],
	"Libya (State of)":["5A"],
	"Lithuania (Republic of)":["LY"],
	"Luxembourg":["LX"],
	"Madagascar (Republic of)":["5R","5S","6X"],
	"Malawi":["7Q"],
	"Malaysia":["9M","9W"],
	"Maldives (Republic of)":["8Q"],
	"Mali (Republic of)":["TZ"],
	"Malta":["9H"],
	"Marshall Islands (Republic of the)":["V7"],
	"Mauritania (Islamic Republic of)":["5T"],
	"Mauritius (Republic of)":["3B"],
	"Mexico":["4A","4B","4C","6D","6E","6F","6G","6H","6I","6J","XA","XB","XC","XD","XE","XF","XG","XH","XI"],
	"Micronesia (Federated States of)":["V6"],
	"Moldova (Republic of)":["ER"],
	"Monaco (Principality of)":["3A"],
	"Mongolia":["JT","JU","JV"],
	"Montenegro":["4O"],
	"Morocco (Kingdom of)":["5C","5D","5E","5F","5G","CN"],
	"Mozambique (Republic of)":["C8","C9"],
	"Myanmar (Union of)":["XY","XZ"],
	"Namibia (Republic of)":["V5"],
	"Nauru (Republic of)":["C2"],
	"Nepal (Federal Democratic Republic of)":["9N"],
	"Netherlands - Aruba":["P4"],
	"Netherlands - Bonaire, Sint Eustatius and Saba, Curaçao, Sint Maarten":["PJ"],
	"Netherlands (Kingdom of the)":["PA","PB","PC","PD","PE","PF","PG","PH","PI", "PJ"],
	"New Zealand - Cook Islands":["E5"],
	"New Zealand - Niue":["E6"],
	"New Zealand":["ZK","ZL","ZM"],
	"Nicaragua":["H6","H7","HT","YN"],
	"Niger (Republic of the)":["5U"],
	"Nigeria (Federal Republic of)":["5N","5O"],
	"North Macedonia (Republic of)":["Z3"],
	"Norway":["3Y","JW","JX","LA","LB","LC","LD","LE","LF","LG","LH","LI","LJ","LK","LL","LM","LN"],
	"Oman (Sultanate of)":["A4"],
	"Pakistan (Islamic Republic of)":["6P","6Q","6R","6S","AP","AQ","AR","AS"],
	"Palau (Republic of)":["T8"],
	"Panama (Republic of)":["3E","3F","H3","H8","H9","HO","HP"],
	"Papua New Guinea":["P2"],
	"Paraguay (Republic of)":["ZP"],
	"Peru":["4T","OA","OB","OC"],
	"Philippines (Republic of the)":["4D","4E","4F","4G","4H","4I","DU","DV","DW","DX","DY","DZ"],
	"Poland (Republic of)":["3Z","HF","SN","SO","SP","SQ","SR"],
	"Portugal":["CQ","CR","CS","CT","CU"],
	"Qatar (State of)":["A7"],
	"Republic of Türkiye":["TA","TB","TC","YM"],
	"Romania":["YO","YP","YQ","YR"],
	"Russian Federation":["RA","RB","RC","RD","RE","RF","RG","RH","RI","RJ","RK","RL","RM","RN","RO","RP","RQ","RR","RS","RT","RU","RV","RW","RX","RY","RZ","UA","UB","UC","UD","UE","UF","UG","UH","UI"],
	"Rwanda (Republic of)":["9X"],
	"Saint Kitts and Nevis (Federation of)":["V4"],
	"Saint Lucia":["J6"],
	"Saint Vincent and the Grenadines":["J8"],
	"Samoa (Independent State of)":["5W"],
	"San Marino (Republic of)":["T7"],
	"Sao Tome and Principe (Democratic Republic of)":["S9"],
	"Saudi Arabia (Kingdom of)":["7Z","8Z","HZ"],
	"Senegal (Republic of)":["6V","6W"],
	"Serbia (Republic of)":["YT","YU"],
	"Seychelles (Republic of)":["S7"],
	"Sierra Leone":["9L"],
	"Singapore (Republic of)":["9V","S6"],
	"Slovak Republic":["OM"],
	"Slovenia (Republic of)":["S5"],
	"Solomon Islands":["H4"],
	"Somalia (Federal Republic of)":["6O","T5"],
	"South Africa (Republic of)":["S8","ZR","ZS","ZT","ZU"],
	"South Sudan (Republic of)":["Z8"],
	"Spain":["AM","AN","AO","EA","EB","EC","ED","EE","EF","EG","EH"],
	"Sri Lanka (Democratic Socialist Republic of)":["4P","4Q","4R","4S"],
	"State of Palestine (In accordance with Resolution 99 Rev. Dubai, 2018)":["E4"],
	"Sudan (Republic of the)":["6T","6U","SSZ","ST"],
	"Suriname (Republic of)":["PZ"],
	"Sweden":["7S","8S","SA","SB","SC","SD","SE","SF","SG","SH","SI","SJ","SK","SL","SM"],
	"Switzerland (Confederation of)":["HB","HE"],
	"Syrian Arab Republic":["6C","YK"],
	"Tajikistan (Republic of)":["EY"],
	"Tanzania (United Republic of)":["5H","5I"],
	"Thailand":["E2","HS"],
	"Timor-Leste (Democratic Republic of)":["4W"],
	"Togolese Republic":["5V"],
	"Tonga (Kingdom of)":["A3"],
	"Trinidad and Tobago":["9Y","9Z"],
	"Tunisia":["3V","TS"],
	"Turkmenistan":["EZ"],
	"Tuvalu":["T2"],
	"Uganda (Republic of)":["5X"],
	"Ukraine":["EM","EN","EO","UR","US","UT","UU","UV","UW","UX","UY","UZ"],
	"United Arab Emirates":["A6"],
	"United Kingdom":["2A","2B","2C","2D","2E","2F","2G","2H","2I","2J","2K","2L","2M","2N","2O","2P","2Q","2R","2S","2T","2U","2V","2W","2X","2Y","2Z","GA","GB","GC","GD","GE","GF","GG","GH","GI","GJ","GK","GL","GM","GN","GO","GP","GQ","GR","GS","GT","GU","GV","GW","GX","GY","GZ","MA","MB","MC","MD","ME","MF","MG","MH","MI","MJ","MK","ML","MM","MN","MO","MP","MQ","MR","MS","MT","MU","MV","MW","MX","MY","MZ","VP","VQ","VS","ZB","ZC","ZD","ZE","ZF","ZG","ZH","ZI","ZJ","ZN","ZO","ZQ"],
	"United Nations":["4U"],
	"USA":["AA","AB","AC","AD","AE","AF","AG","AH","AI","AJ","AK","AL","KA","KB","KC","KD","KE","KF","KG","KH","KI","KJ","KK","KL","KM","KN","KO","KP","KQ","KR","KS","KT","KU","KV","KW","KX","KY","KZ","NA","NB","NC","ND","NE","NF","NG","NH","NI","NJ","NK","NL","NM","NN","NO","NP","NQ","NR","NS","NT","NU","NV","NW","NX","NY","NZ","WA","WB","WC","WD","WE","WF","WG","WH","WI","WJ","WK","WL","WM","WN","WO","WP","WQ","WR","WS","WT","WU","WV","WW","WX","WY","WZ"],
	"Uruguay (Eastern Republic of)":["CV","CW","CX"],
	"Uzbekistan (Republic of)":["UJ","UK","UL","UM"],
	"Vanuatu (Republic of)":["YJ"],
	"Vatican City State":["HV"],
	"Venezuela (Bolivarian Republic of)":["4M","YV","YW","YX","YY"],
	"Viet Nam (Socialist Republic of)":["3W","XV"],
	"Yemen (Republic of)":["7O"],
	"Zambia (Republic of)":["9I","9J"],
	"Zimbabwe (Republic of)":["Z2"]
}
